export default{
    USER_INFORMATION:'USER_INFORMATION',
    STUDENT_LIST:'STUDENTLIST',
    SELECTED_STUDENT_DETAILS:'SELECTED_STUDENT_DETAILS',
    SESSION_DETAILS:'SESSION_DETAILS',
    TOKEN: 'TOKEN'

}